stages:
  - lint
  - test
  - build
  - push

variables:
  DOCKER_IMAGE: docker.io/$DOCKER_USERNAME/app
  DOCKER_TAG: latest

before_script:
  - npm install

lint:
  stage: lint
  image: node:20-alpine
  script:
    - npm run lint

test:
  stage: test
  image: node:20-alpine
  script:
    - npm run test

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
  only:
    - main

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - main
